// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class ChangeResolutionLog
{
    public string TsaId { get; set; }

    public string TsaSubId { get; set; }

    public string ChangeId { get; set; }

    public int ChangeLogTypeId { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public string Function { get; set; }

    public string SubFunction { get; set; }

    public string ServiceName { get; set; }

    public string DetailedServiceDescription { get; set; }

    public string TsaVsRtsa { get; set; }

    public string PrimaryOwner { get; set; }

    public string ReceiverOwner { get; set; }

    public string ServiceExceptions { get; set; }

    public string ServiceLocation { get; set; }

    public string EstimatedDurationText { get; set; }

    public string Assumptions { get; set; }

    public string ExceptionsToMonthlyInvoice { get; set; }

    public string ExceptionsTo30DayPayment { get; set; }

    public string NoticeOfTerminationText { get; set; }

    public string ExceptionsReOwnershipIp { get; set; }

    public string TsaExitApproach { get; set; }

    public string KnownTsaExitCosts { get; set; }

    public string KnownDependencies { get; set; }

    public string UnitDescription { get; set; }

    public string NumOfUnits { get; set; }

    public string PricePerUnit { get; set; }

    public string CostType { get; set; }

    public string AdditionalPricingComments { get; set; }

    public string TaxDetermination { get; set; }

    public string OptionExercisedFlag { get; set; }

    public int? ActiveOptionDurationExercised { get; set; }

    public decimal? MonthlyCostForecast { get; set; }

    public DateTime CreatedDate { get; set; }

    public long CreatedUserId { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public long LastModifiedUserId { get; set; }

    public int FileRepositoryId { get; set; }

    public long ChangeResolutionLogId { get; set; }

    public DateOnly? ActiveEndDate { get; set; }

    public string Currency { get; set; }

    public decimal? ExitCostAmount { get; set; }

    public int? MaxOptionDuration { get; set; }

    public int? NoticeOfTermNum { get; set; }

    public string OptionFlag { get; set; }

    public string ProviderOwner { get; set; }

    public string SeparationOrStandalone { get; set; }

    public virtual LogType ChangeLogType { get; set; }

    public virtual User CreatedUser { get; set; }

    public virtual FileRepository FileRepository { get; set; }

    public virtual User LastModifiedUser { get; set; }

    public virtual TsaSchedule TsaSub { get; set; }
}