// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class ChangeLog
{
    public int ChangeLogId { get; set; }

    public string TsaId { get; set; }

    public string TsaSubId { get; set; }

    public string ChangeId { get; set; }

    public DateOnly? ChangeDate { get; set; }

    public int ChangeLogTypeId { get; set; }

    public int ChangeLogStatusId { get; set; }

    public long RequestedByUserId { get; set; }

    public long SubmittedByUserId { get; set; }

    public string Comments { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public long CreatedUserId { get; set; }

    public long LastModifiedUserId { get; set; }

    public int Revision { get; set; }

    public virtual ICollection<ChangeLogFile> ChangeLogFiles { get; set; } = new List<ChangeLogFile>();

    public virtual LogStatus ChangeLogStatus { get; set; }

    public virtual LogType ChangeLogType { get; set; }

    public virtual User CreatedUser { get; set; }

    public virtual User LastModifiedUser { get; set; }

    public virtual User RequestedByUser { get; set; }

    public virtual User SubmittedByUser { get; set; }

    public virtual TsaSchedule TsaSub { get; set; }
}