// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class DisputeLogFile
{
    public int DisputeLogFileId { get; set; }

    public int DisputeLogId { get; set; }

    public int FileRepositoryId { get; set; }

    public virtual DisputeLog DisputeLog { get; set; }

    public virtual FileRepository FileRepository { get; set; }
}