// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class DisputeType
{
    public int DisputeTypeId { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<DisputeLog> DisputeLogs { get; set; } = new List<DisputeLog>();
}