// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class ExcelFailure
{
    public long Id { get; set; }

    public string Errors { get; set; }

    public string StackTrace { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public long? ExcelRow { get; set; }

    public string CellData { get; set; }

    public DateTime CreatedDate { get; set; }

    public long? CreatedUserId { get; set; }

    public virtual User CreatedUser { get; set; }
}