// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class FileType
{
    public int FileTypeId { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<FileRepository> FileRepositories { get; set; } = new List<FileRepository>();
}