// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TsaData.Models
{
    public partial class get_activity_reportResult
    {
        public string id { get; set; }
        public DateTime? created_date { get; set; }
        public string tsa_id { get; set; }
        public string tsa_sub_id { get; set; }
        public string function { get; set; }
        public string primary_owner { get; set; }
        public string service_name { get; set; }
        public DateOnly? effective_date { get; set; }
        public string log_type { get; set; }
        public string log_status { get; set; }
        public string comments { get; set; }
        public string submitted_by { get; set; }
        public DateOnly? invoice_period_end_date { get; set; }
        public string invoice_number { get; set; }
        [Column("invoice_amount", TypeName = "decimal(18,2)")]
        public decimal? invoice_amount { get; set; }
        public decimal? agreed_cost { get; set; }
    }
}
