// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class Invoice
{
    public int Id { get; set; }

    public string TsaSubId { get; set; }

    public string TsaId { get; set; }

    public string InvoiceNumber { get; set; }

    public DateOnly? InvoiceDate { get; set; }

    public string InvoiceFrequency { get; set; }

    public DateOnly? InvoicePeriodStartDate { get; set; }

    public DateOnly? InvoicePeriodEndDate { get; set; }

    public DateOnly? InvoiceDueDate { get; set; }

    public DateOnly? ServicePeriod { get; set; }

    public decimal? Markup { get; set; }

    public DateTime CreatedDate { get; set; }

    public long CreatedUserId { get; set; }

    public int FileRepositoryId { get; set; }

    public string Currency { get; set; }

    public decimal? MarkupUsd { get; set; }

    public decimal? UsdExchangeRate { get; set; }

    public decimal? NumberOfUnits { get; set; }

    public string UnitOfMeasure { get; set; }

    public decimal? Cost { get; set; }

    public decimal? CostUsd { get; set; }

    public decimal? InvoiceAmount { get; set; }

    public decimal? InvoiceAmountUsd { get; set; }

    public string AnkuraInvoice { get; set; }

    public string ReferenceInvoiceNumber { get; set; }

    public virtual User CreatedUser { get; set; }

    public virtual FileRepository FileRepository { get; set; }

    public virtual TsaSchedule TsaSub { get; set; }
}