// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TsaData.Models;

namespace TsaData.Models
{
    public partial interface ITsaContextProcedures
    {
        Task<List<get_activity_reportResult>> get_activity_reportAsync(string LogStatuses, DateTime? FromDate, DateTime? ToDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
