// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class LogType
{
    public int LogTypeId { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<AddLog> AddLogs { get; set; } = new List<AddLog>();

    public virtual ICollection<ChangeLog> ChangeLogs { get; set; } = new List<ChangeLog>();

    public virtual ICollection<ChangeResolutionLog> ChangeResolutionLogs { get; set; } = new List<ChangeResolutionLog>();

    public virtual ICollection<LogStatus> LogStatuses { get; set; } = new List<LogStatus>();
}