// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public string TsaSubId { get; set; }

    public string TsaId { get; set; }

    public string InvoiceNumber { get; set; }

    public string PaymentType { get; set; }

    public decimal? PaymentAmount { get; set; }

    public DateOnly? PaymentDate { get; set; }

    public string TransactionId { get; set; }

    public DateTime CreatedDate { get; set; }

    public long CreatedUserId { get; set; }

    public int FileRepositoryId { get; set; }

    public string BankAccountFrom { get; set; }

    public string BankAccountTo { get; set; }

    public string Currency { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? UsdConversion { get; set; }

    public string AnkuraInvoice { get; set; }

    public virtual User CreatedUser { get; set; }

    public virtual FileRepository FileRepository { get; set; }

    public virtual TsaSchedule TsaSub { get; set; }
}