// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class Role
{
    public long Id { get; set; }

    public string Name { get; set; }

    public bool Disabled { get; set; }

    public DateTime? DisabledAt { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}