// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class SellSideNotificationDispute
{
    public int NotificationDisputeId { get; set; }

    public string TsaId { get; set; }

    public string TsaSubId { get; set; }

    public string PrimaryOwner { get; set; }

    public string ServiceName { get; set; }

    public string Type { get; set; }

    public string InvoiceNumber { get; set; }

    public decimal? InvoiceAmount { get; set; }

    public string ActionItem { get; set; }

    public int FileRepositoryId { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public long LastModifiedUserId { get; set; }

    public DateTime? InvoicePeriodEndDate { get; set; }

    public DateTime? InvoicePeriodStartDate { get; set; }

    public string InvoiceCurrency { get; set; }

    public virtual FileRepository FileRepository { get; set; }

    public virtual User LastModifiedUser { get; set; }

    public virtual TsaSchedule TsaSub { get; set; }
}