// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class SellSideNotificationChange
{
    public int NotificationChangeId { get; set; }

    public string TsaId { get; set; }

    public string TsaSubId { get; set; }

    public string PrimaryOwner { get; set; }

    public string ServiceName { get; set; }

    public string Status { get; set; }

    public string ActionItem { get; set; }

    public int FileRepositoryId { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public long LastModifiedUserId { get; set; }

    public virtual FileRepository FileRepository { get; set; }

    public virtual User LastModifiedUser { get; set; }

    public virtual TsaSchedule TsaSub { get; set; }
}