// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TsaData.Models;

namespace TsaData.Models
{
    public partial class TsaContext
    {
        private ITsaContextProcedures _procedures;

        public virtual ITsaContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TsaContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITsaContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TsaContextProcedures : ITsaContextProcedures
    {
        private readonly TsaContext _context;

        public TsaContextProcedures(TsaContext context)
        {
            _context = context;
        }

        public virtual async Task<List<get_activity_reportResult>> get_activity_reportAsync(string LogStatuses, DateTime? FromDate, DateTime? ToDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LogStatuses",
                    Size = 100,
                    Value = LogStatuses ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "FromDate",
                    Value = FromDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "ToDate",
                    Value = ToDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<get_activity_reportResult>("EXEC @returnValue = [dbo].[get_activity_report] @LogStatuses = @LogStatuses, @FromDate = @FromDate, @ToDate = @ToDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
