// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class UserRole
{
    public long Id { get; set; }

    public long RoleId { get; set; }

    public long UserId { get; set; }

    public virtual Role Role { get; set; }

    public virtual User User { get; set; }
}