// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class User
{
    public long Id { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public bool Disabled { get; set; }

    public DateTime? DisabledAt { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public virtual ICollection<AddLog> AddLogCreatedUsers { get; set; } = new List<AddLog>();

    public virtual ICollection<AddLog> AddLogLastModifiedUsers { get; set; } = new List<AddLog>();

    public virtual ICollection<AddLog> AddLogRequestedByUsers { get; set; } = new List<AddLog>();

    public virtual ICollection<AddLog> AddLogSubmittedByUsers { get; set; } = new List<AddLog>();

    public virtual ICollection<ChangeLog> ChangeLogCreatedUsers { get; set; } = new List<ChangeLog>();

    public virtual ICollection<ChangeLog> ChangeLogLastModifiedUsers { get; set; } = new List<ChangeLog>();

    public virtual ICollection<ChangeLog> ChangeLogRequestedByUsers { get; set; } = new List<ChangeLog>();

    public virtual ICollection<ChangeLog> ChangeLogSubmittedByUsers { get; set; } = new List<ChangeLog>();

    public virtual ICollection<ChangeResolutionLog> ChangeResolutionLogCreatedUsers { get; set; } = new List<ChangeResolutionLog>();

    public virtual ICollection<ChangeResolutionLog> ChangeResolutionLogLastModifiedUsers { get; set; } = new List<ChangeResolutionLog>();

    public virtual ICollection<DisputeLog> DisputeLogCreatedUsers { get; set; } = new List<DisputeLog>();

    public virtual ICollection<DisputeLog> DisputeLogLastModifiedUsers { get; set; } = new List<DisputeLog>();

    public virtual ICollection<DisputeLog> DisputeLogRequestedByUsers { get; set; } = new List<DisputeLog>();

    public virtual ICollection<DisputeLog> DisputeLogSubmittedByUsers { get; set; } = new List<DisputeLog>();

    public virtual ICollection<FileRepository> FileRepositories { get; set; } = new List<FileRepository>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<SellSideNotificationChange> SellSideNotificationChanges { get; set; } = new List<SellSideNotificationChange>();

    public virtual ICollection<SellSideNotificationDispute> SellSideNotificationDisputes { get; set; } = new List<SellSideNotificationDispute>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}