// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class VActivityReport
{
    public string Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string TsaId { get; set; }

    public string TsaSubId { get; set; }

    public string Function { get; set; }

    public string PrimaryOwner { get; set; }

    public string ServiceName { get; set; }

    public string TsaVsRtsa { get; set; }

    public DateOnly? EffectiveDate { get; set; }

    public string LogType { get; set; }

    public string LogStatus { get; set; }

    public string Comments { get; set; }

    public string SubmittedBy { get; set; }

    public DateOnly? InvoicePeriodEndDate { get; set; }

    public string InvoiceNumber { get; set; }

    public decimal? InvoiceAmount { get; set; }

    public decimal? AgreedCost { get; set; }
}