// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class VAddLog
{
    public int AddLogId { get; set; }

    public string TsaId { get; set; }

    public string TsaSubId { get; set; }

    public DateOnly? ChangeDate { get; set; }

    public int ChangeLogTypeId { get; set; }

    public int ChangeLogStatusId { get; set; }

    public long RequestedByUserId { get; set; }

    public long SubmittedByUserId { get; set; }

    public string Comments { get; set; }

    public DateTime CreatedDate { get; set; }

    public long CreatedUserId { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public long LastModifiedUserId { get; set; }

    public int Revision { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidTo { get; set; }

    public string TsaSubIds { get; set; }

    public int AddTypeId { get; set; }

    public string AddId { get; set; }

    public string ChangeLogType { get; set; }

    public string ChangeLogStatus { get; set; }

    public string PrimaryOwner { get; set; }

    public string ReceiverOwner { get; set; }

    public string ServiceName { get; set; }

    public string Function { get; set; }

    public string TsaVsRtsa { get; set; }
}