// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class VDisputeLog
{
    public int DisputeLogId { get; set; }

    public string TsaSubId { get; set; }

    public string TsaId { get; set; }

    public DateOnly? SubmissionDate { get; set; }

    public int DisputeTypeId { get; set; }

    public string DisputeId { get; set; }

    public string InvoiceNumber { get; set; }

    public long RequestedByUserId { get; set; }

    public long SubmittedByUserId { get; set; }

    public int DisputeDiscrepancyId { get; set; }

    public string Comments { get; set; }

    public decimal? AgreedCost { get; set; }

    public DateTime CreatedDate { get; set; }

    public long CreatedUserId { get; set; }

    public DateTime LastModifiedDate { get; set; }

    public long LastModifiedUserId { get; set; }

    public int Revision { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidTo { get; set; }

    public string Currency { get; set; }

    public string DisputeType { get; set; }

    public string DisputeDiscrepancy { get; set; }

    public string ServiceName { get; set; }

    public string Function { get; set; }

    public string UnitDescription { get; set; }

    public string PrimaryOwner { get; set; }

    public string TsaVsRtsa { get; set; }

    public decimal? MonthlyPricing { get; set; }

    public decimal? MonthlyCostForecastInclActuals { get; set; }

    public double? MonthlyCostForecastProratedInclActuals { get; set; }

    public decimal? InvoiceAmountUsd { get; set; }

    public DateOnly? ServicePeriod { get; set; }
}