// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class VInputStreamSummary
{
    public int? FileRepositoryId { get; set; }

    public int FileTypeId { get; set; }

    public string FileTypeName { get; set; }

    public string FileName { get; set; }

    public DateTime? UploadedDate { get; set; }

    public string UploadedBy { get; set; }

    public int? TotalCount { get; set; }
}