// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class VLogTypeStatus
{
    public string Id { get; set; }

    public int? LogTypeId { get; set; }

    public string LogTypeName { get; set; }

    public int? LogStatusId { get; set; }

    public string LogStatusName { get; set; }

    public string Description { get; set; }
}