// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TsaData.Models;

public partial class VMonthlyInvEstPayDisp
{
    public string TsaSubId { get; set; }

    public string TsaId { get; set; }

    public DateOnly? ServicePeriod { get; set; }

    public string SeparationOrStandalone { get; set; }

    public string Function { get; set; }

    public string CostType { get; set; }

    public string TsaVsRtsa { get; set; }

    public decimal? MonthlyInvoiceAmount { get; set; }

    public decimal? MonthlyInvoiceUsdConversion { get; set; }

    public decimal? MonthlyPricing { get; set; }

    public decimal? MonthlyCostForecast { get; set; }

    public double? MonthlyCostForecastProrated { get; set; }

    public decimal? PaymentAmount { get; set; }

    public decimal? PaymentUsdConversion { get; set; }
}